#!/bin/bash
# Ensure SDDM is configured for gaming mode

SDDM_CONF="/etc/sddm.conf.d/zz-steamos-autologin.conf"

mkdir -p "$(dirname "$SDDM_CONF")"
cat > "/etc/sddm.conf.d/zz-steamos-autologin.conf" <<EOF
[Autologin]
Session=gamescope-session.desktop
EOF

exit 0
